### ISSUE TITLE
cocoalib fails to install

### ISSUE THREAD

**Issue by sarming** [moves-rwth/homebrew-misc#1]
On my macOS 10.12.6 system cocoalib fails to install with the delightfully cryptic error message:
`Good news: all CoCoALib tests passed`
Digging deeper in the logs I found three instances of: `fatal error: 'boost/tr1/memory.hpp' file not found`
Here is what I put into the formula before the `./configure` step to fix it:
```ruby
for file in ["Lexer", "Main", "LineProviders"]
      inreplace "src/CoCoa-5/#{file}.C", "boost/tr1/memory.hpp","memory"
end
```

I don't know if this is specific to me, I thought leave it here in case anyone else runs into the same problem.

**Comment by cdehnert** [comment]
This definitely is not specific to you, so thanks for leaving your comment here. We were aware of the problem, but decided to ignore it until CoCoALib brings out a new release that solves the problem, which they agreed to do a while back. Thanks to your fix, it should now build again!
